### PR TITLE
Correct default values for read and write timeouts

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Correct default values for read and write timeouts
- They are now set to TimeSpan.MaxValue instead of TimeSpan.Zero which (wrongly) was causing a timeout exception being thrown

## Motivation and Context
- Fixes/Closes/Resolves nanoFramework/Home#318

## How Has This Been Tested?
- Serial sample app from sampes repo

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: josesimoes <jose.simoes@eclo.solutions>

### CODE REVIEW

**Comment by MikroBusNet** [comment]
> Am I misinterpreting the design and the spirit of the .NET API?
Of course not.

But then I think that "you" (we) have replaced plague with cholera. In the first version, we had an exception because of too small timeout. Now we get an infinite wait.
Had I the choice, I would have chosen the exception, because it returns control back to the managed app and can be handled easily.

My proposal of 50ms default value (it could be anything else) was more an help for the programmer to have their program working at first launch without being hung without knowing what's happening. If he wants to play with timeouts, then it's up to him and here he will set the values at will.

Right now, I have the feeling that I am punished because I did not think to set timeouts. The punishment was less severe with 0ms.

But that's the API, .NET, etc... So...

But then... it is the expected behaviour to speed up communications by setting small read timeouts ?

**Comment by josesimoes** [comment]
> But then I think that "you" (we) have replaced plague with cholera
Oh my!! I don't think I'm prepared for that!! 😆 😆 

It's my belief that that possible frustration can be minimized with a good sample explaining and pointing out that.
If you ask me the exception of a timeout was at best misleading. In fact for Store(), there wasn't any timeout and the operation did occur as expected. The exception was the result of the call to the waiter of the scheduler.

As fot speeding up communications: the read timeout doesn't have any influence on that. As soon as a read is setup it will happen as fast as the hardware permits. The timeout only plays a role if the requested amount of bytes isn't read during the expected time. It's just there so the operation doesn't "wait forever" for something to arrive at the UART.
Sometimes that can be intended outcome, e.g. on a COM interface for a radio that is waiting for a packet to arrive, which will occur at an undetermined time in the future. On those use cases the timeout infinite is the way to go.

**Comment by MikroBusNet** [comment]
I think I will have to disagree on the read timeout influence. I have a serial display (Vizic SmartGPU2) and it is obvious that it is (was ?) running slower when a big read timeout is set.

Perhaps you could check on your side by setting a "huge" read timeout (something like 2 or 4 sec) so that the effect becomes obvious with many successive reads. Even if you receive the expected number of bytes, the read does not return until the timeout value is reached.
Perhaps it is fixed now, I will have to check that on my side. If this is the case, then ignore my comment about this.

**Comment by josesimoes** [comment]
That's not the intended behaviour, at all!
If that is happening it's a bug.

(can't remember testing for the exact scenario you're describing, so it could still be happening)

**Comment by MikroBusNet** [comment]
More tests will be needed, I think.

Increasing the read timeout from 25ms to 500ms seems to hang the board. It even needs a complete reflash as VS can't deploy anymore.

I have noticed a huge increase in Write speed, however. Without even changing the Write timeout. "Before the last changes", there were only small differences, although clearly noticeable, between 57600 and 512000 bps, for example. Now, the speed increase is somehow proportional to the baudrate increase.

**Comment by MikroBusNet** [comment]
Another strange thing is that at not-so-high speeds (>= 115200 bps) I have to insert a _Thread.Sleep(5)_ at some point in my test program so that the complete set of data/commands is sent to the serial device (a display). With that delay, all data is transmitted correctly, even at 2.000.000 bps.

At lower speed, that delay is not needed. Increasing/decreasing the Write timeout does not change anything.

Here is the code :
```
private static void TestSmartGPU2()
        {
            var display = new SmartGpu2(Hardware.SocketTwo, SmartGpu2.DisplayType.Lcd480X320);

            SmartGpu2.SmartGpuReponse response = display.SetBaudRate(SmartGpu2.BaudRate.BaudRate115200);
            //SmartGpu2.SmartGpuReponse response;

            var deb = DateTime.UtcNow;

            response = display.SetEraseBackColor(0x0000);
            response = display.SetTextColor(0xFFE0);
            response = display.SetTextFontSize(SmartGpu2.FontSize.Font2);
            display.SetTextBackgroundColor(0x001F);
            display.SetTextBackgroundFill(SmartGpu2.FillGeometry.Filled);
            response = display.EraseScreen();
            response = display.DrawString(0, 0, display.MaxX, display.MaxY, "SmartGPU2 on NanoFramework", out UInt16 spc);
            display.SetTextBackgroundColor(0b00000_011111_00000);  // RGB565 Green
            display.SetTextBackgroundFill(SmartGpu2.FillGeometry.Filled);
            response = display.SetTextColor(0b11111_111111_11111);
            response = display.DrawString(0, 30, display.MaxX, display.MaxY, 98.1234567891.ToString("F10"), out ushort spc2);
            response = display.DrawArc(200, 100, 50, 20, SmartGpu2.Arcquadrant.Quadrant1, 0xF800, SmartGpu2.FillGeometry.Filled);
            response = display.DrawArc(200, 100, 50, 20, SmartGpu2.Arcquadrant.Quadrant2, 0x00F8, SmartGpu2.FillGeometry.Unfilled);
            response = display.DrawArc(200, 100, 50, 20, SmartGpu2.Arcquadrant.Quadrant3, 0x001F, SmartGpu2.FillGeometry.Filled);
            response = display.DrawArc(200, 100, 50, 20, SmartGpu2.Arcquadrant.Quadrant4, 0x07E0, SmartGpu2.FillGeometry.Unfilled);
            response = display.DrawCircle(200, 100, 60, 0xF8FE, SmartGpu2.FillGeometry.Unfilled);
            response = display.DrawCircle(100, 100, 50, 0xFFE0, SmartGpu2.FillGeometry.Filled);
            display.SetTextBackgroundColor(0x0000);
            display.SetTextColor(0x07FF);
            display.SetTextFontSize(SmartGpu2.FontSize.Font7);
            
            for (ushort i = 0; i < 240; i++)
            {
                display.DrawPixel(i, 160, 0xF800);
                display.DrawString(320, 0, display.MaxX, display.MaxY, i.ToString("G4"), out ushort spc4);
            }

            response = display.DrawGradientRectangle(0, 200, 240, 319, 0xF800, 0x001F, SmartGpu2.OrientationParameter.Horizontal);
            //Thread.Sleep(5);
            response = display.DrawGradientRectangle(50, 240, 140, 280, 0xFFE0, 0x06FF, SmartGpu2.OrientationParameter.Vertical);
            response = display.DrawRoundRectangle(242, 160, display.MaxX, display.MaxY, 8, 0x07E0, SmartGpu2.FillGeometry.Unfilled);
            response = display.DrawRoundRectangle(300, 180, 400, 260, 6, 0xA7E0, SmartGpu2.FillGeometry.Filled);
            response = display.DrawTriangle(400, 10, 320, 140, 460, 80, 0x0F0A, SmartGpu2.FillGeometry.Unfilled);
            response = display.DrawTriangle(400, 20, 340, 120, 430, 80, 0x2F0A, SmartGpu2.FillGeometry.Filled);

            WriteLine("Duration : " + DateTime.UtcNow.Subtract(deb));
        }
```
Near the end, you can see the _Thread.Sleep()_ call, which is commented here. In this case, the data/commands sent below are not executed, which means they are not sent.
If I remove the comment, and activate the sleep, then everything is fine and all the commands are sent/executed, no matter the baudrate, up to 2.000.000 bps.

I suspect some internal buffer corruption or something similar. Something that might happen when a buffer is full and it does not have time to be empty or something like this. I am not familiar with the serial thing.

**Comment by MikroBusNet** [comment]
About the comment just above : it hangs the board when using the Vizic SmartGPu2 serial display.
If I use the Wifi3 Click board from MikroElektronika (module using ESP8266), then response time is slow and I am missing incoming data.
In the latter test (the one with ESP8266), I get correct and complete data with 50ms read timeout.

So this value has some influence on the result of a read operation. Whether it is an expected behaviour or not, I don't know.

**Pull request merged**
